version: '3.8'

services:
  postgresql_server:
    image: postgres:13-alpine
    container_name: db_server
    env_file:
      - .env
    volumes:
      - dbServerVolume:/docker/data/postgresql/
    networks:
      serviceNetwork:
        ipv4_address: 192.168.2.3
    ports:
      - "5432:5432"
    restart: unless-stopped

  redis_server:
    image: redis:6.2.1
    container_name: redis_server
    volumes:
      - redisVolume:/docker/data/redis/
    networks:
      serviceNetwork:
        ipv4_address: 192.168.2.5
    ports:
      - "6379:6379"
    restart: unless-stopped

# Network definition
networks:
  serviceNetwork:
    name: serviceNetwork
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.2.0/24

# Volume definition
volumes:
  dbServerVolume:
    name: dbServerVolume
  redisVolume:
    name: redisVolume